# Generated by Django 3.0.7 on 2020-10-21 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='course_slug',
            field=models.SlugField(db_column='CourseSlug', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='section_end_date',
            field=models.DateField(db_column='SectionEndate', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='section_start_date',
            field=models.DateField(db_column='SectionStartDate', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
