# Generated by Django 3.0.7 on 2020-10-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_auto_20201021_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='course_slug',
            field=models.CharField(db_column='CourseSlug', max_length=256),
        ),
    ]
