# Generated by Django 3.0.7 on 2020-10-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_auto_20201021_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='section_end_date',
            field=models.DateTimeField(db_column='SectionEndate'),
        ),
        migrations.AlterField(
            model_name='product',
            name='section_start_date',
            field=models.DateTimeField(db_column='SectionStartDate'),
        ),
    ]
