# Generated by Django 3.0.7 on 2020-10-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_auto_20201021_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='section_end_date',
            field=models.DateTimeField(blank=True, db_column='SectionEndate', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='section_start_date',
            field=models.DateTimeField(blank=True, db_column='SectionStartDate', null=True),
        ),
    ]
