# Generated by Django 3.0.7 on 2020-10-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0005_auto_20201021_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolment',
            name='course_id',
            field=models.CharField(db_column='CourseID', max_length=256),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='section_id',
            field=models.CharField(db_column='SectionID', max_length=256),
        ),
    ]
