# Generated by Django 3.0.7 on 2020-10-21 13:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0006_auto_20201021_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('active_status', models.BooleanField(db_column='ActiveStatus', default=True)),
                ('id', models.UUIDField(db_column='PaymentTransactionID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(db_column='TransactionType', max_length=16)),
                ('transaction_code', models.CharField(db_column='TransactionCode', max_length=256)),
                ('transaction_time', models.DateTimeField(auto_now_add=True, db_column='TransactionTime')),
                ('currency_code', models.CharField(db_column='CurrencyCode', max_length=256)),
                ('amount', models.FloatField(db_column='Amount')),
                ('status', models.CharField(db_column='Status', max_length=16)),
                ('transaction_reference', models.CharField(db_column='TransactionReference', max_length=256)),
                ('transaction_detail', django.contrib.postgres.fields.jsonb.JSONField(db_column='TransactionDetail')),
                ('payment', models.ForeignKey(db_column='PaymentID', on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='enrollment.Payment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
