# Generated by Django 3.0.7 on 2020-10-21 13:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0007_paymenttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_code',
            field=models.CharField(blank=True, db_column='TransactionCode', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_detail',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='TransactionDetail', null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_reference',
            field=models.CharField(blank=True, db_column='TransactionReference', max_length=256, null=True),
        ),
    ]
